routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['session.login'])->group(function () {
    Route::get('/', function () {
        return view('dashboard.index');
    })->name('dashboard');
    Route::get('/login', 'AuthController@login')->name('login');
    Route::post('/login', 'ConsumeApiController@attemptLogin')->name('post.login');
    Route::get('/logout', 'AuthController@logout')->name('logout');

    Route::get('/ticket/report', 'TicketController@report')->name('ticket.report');
    Route::get('/ticket/beli', 'TicketController@create')->name('ticket.create');
    Route::post('/ticket/beli', 'TicketController@beli')->name('ticket.beli');
    Route::resource('user', 'UserController');
});

resources/views/user-management/create.blade.php
@extends('layout.main')
@section('menu-user-management', 'active')
@section('content')
    <div class="container">
        <h1>
            Tambah User
        </h1>
        {{-- @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>
                            {{ $error }}
                        </li>
                    @endforeach
                </ul>
            </div>
        @endif --}}
        <form action="{{ route('user.store') }}" method="POST">
            @csrf
            <div class="">
                <div class="form-group">
                    <label for="name">
                        Nama
                    </label>
                    <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}"
                        id="name" placeholder="Enter nama" value="{{ old('name') }}">

                    @error('name')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email"
                        class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" id="email"
                        placeholder="email" value="{{ old('email') }}">
                    @error('email')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password"
                        class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }}" id="password"
                        placeholder="password">
                    @error('password')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="confirmpassowd">Confirm Password</label>
                    <input type="password" name="confirmpassword"
                        class="form-control {{ $errors->has('confirmpassword') ? 'is-invalid' : '' }}" id="confirmpassword"
                        placeholder="confirm password">
                    @error('confirmpassword')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

            </div>
            <!-- /.card-body -->
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{{ route('user.index') }}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
@endsection

resources/views/user-management/edit.blade.php
@extends('layout.main')
@section('menu-user-management', 'active')
@section('content')
    <div class="container">
        <h1>
            Update User
        </h1>
        {{-- @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>
                            {{ $error }}
                        </li>
                    @endforeach
                </ul>
            </div>
        @endif --}}
        <form action="{{ route('user.update', $data['id']) }}" method="POST">
            @csrf
            @method('PUT')
            <input type="hidden" name="id" value="{{ $data['id'] }}">
            <div class="">
                <div class="form-group">
                    <label for="name">
                        Nama
                    </label>
                    <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}"
                        id="name" placeholder="Enter nama" value="{{ $data['name'] }}">

                    @error('name')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email"
                        class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" id="email"
                        placeholder="email" value="{{ $data['email'] }}">
                    @error('email')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password"
                        class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }}" id="password"
                        placeholder="password">
                    @error('password')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="confirmpassowd">Confirm Password</label>
                    <input type="password" name="confirmpassword"
                        class="form-control {{ $errors->has('confirmpassword') ? 'is-invalid' : '' }}" id="confirmpassword"
                        placeholder="confirm password">
                    @error('confirmpassword')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

            </div>
            <!-- /.card-body -->
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{{ route('user.index') }}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
@endsection

resources/views/user-management/index.blade.php
@extends('layout.main')
@section('menu-user-management', 'active')
@section('content')
    <div class="d-flex justify-content-between align-items-center">
        <h1>
            Master Admin
        </h1>
        <a href="{{ route('user.create') }}" class="btn btn-primary">
            Tambah
        </a>
    </div>


    <table class="table table-bordered">
        <thead>
            <tr>
                <th style="width: 10px">#</th>
                <th>Nama</th>
                <th>Email</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>


            @foreach ($data as $value)
                <tr>
                    <td>{{ $loop->iteration }}.</td>
                    <td>{{ $value['name'] }}</td>

                    <td>{{ $value['email'] }}</td>
                    <td>

                        <a href="{{ route('user.edit', $value['id']) }}" class="btn btn-sm btn-warning">Edit</a>
                        <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal"
                            data-id="{{ $value['id'] }}" data-bs-target="#modaldelete">
                            Delete
                        </button>
                    </td>
                </tr>
            @endforeach

        </tbody>
    </table>

    {{ $data->links() }}

    <div class="modal" tabindex="-1" id="modaldelete">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p id="modal-text"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="/" method="POST" style="display: inline" id="form-delete">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        const modaldelete = document.getElementById('modaldelete');
        const modaltext = document.getElementById('modal-text');
        const btnDelete = document.querySelectorAll('.btn-danger');
        const formDelete = document.getElementById('form-delete');

        btnDelete.forEach((btn) => {
            btn.addEventListener('click', function() {
                const id = this.getAttribute('data-id');
                console.log(id);

                modaltext.innerHTML = `Apakah anda yakin ingin menghapus data ini?`;
                // "{{ route('user.destroy', $value['id']) }}"
                formDelete.action = "{{ route('user.destroy', $value['id']) }}"
            });
        });
    </script>
@endsection